  0%|                                                                                                                                                                                                                           | 0/45900 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/zhiqi/CS839-Project/small_model.py", line 113, in <module>
    initialize_training(
  File "/home/zhiqi/CS839-Project/small_model.py", line 90, in initialize_training
    trainer.train()
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/transformers/trainer.py", line 2123, in train
    return inner_training_loop(
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/transformers/trainer.py", line 2481, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
TypeError: DreamTrainer.training_step() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "/home/zhiqi/CS839-Project/small_model.py", line 113, in <module>
    initialize_training(
  File "/home/zhiqi/CS839-Project/small_model.py", line 90, in initialize_training
    trainer.train()
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/transformers/trainer.py", line 2123, in train
    return inner_training_loop(
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/transformers/trainer.py", line 2481, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
TypeError: DreamTrainer.training_step() takes 3 positional arguments but 4 were given
