  0%|                                                                                                                                                                                                                           | 0/13770 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 776, in convert_to_tensors
    tensor = as_tensor(value)
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 738, in as_tensor
    return torch.tensor(value)
ValueError: expected sequence of length 11 at dim 1 (got 115)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zhiqi/CS839-Project/small_model.py", line 86, in <module>
    trainer.train()
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/transformers/trainer.py", line 2123, in train
    return inner_training_loop(
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/transformers/trainer.py", line 2427, in _inner_training_loop
    batch_samples, num_items_in_batch = self.get_batch_samples(epoch_iterator, num_batches)
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/transformers/trainer.py", line 5045, in get_batch_samples
    batch_samples += [next(epoch_iterator)]
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/accelerate/data_loader.py", line 552, in __iter__
    current_batch = next(dataloader_iter)
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 673, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 55, in fetch
    return self.collate_fn(data)
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/transformers/data/data_collator.py", line 45, in __call__
    return self.torch_call(features)
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/transformers/data/data_collator.py", line 807, in torch_call
    batch = pad_without_fast_tokenizer_warning(
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/transformers/data/data_collator.py", line 66, in pad_without_fast_tokenizer_warning
    padded = tokenizer.pad(*pad_args, **pad_kwargs)
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 3541, in pad
    return BatchEncoding(batch_outputs, tensor_type=return_tensors)
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 240, in __init__
    self.convert_to_tensors(tensor_type=tensor_type, prepend_batch_axis=prepend_batch_axis)
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 792, in convert_to_tensors
    raise ValueError(
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (`labels` in this case) have excessive nesting (inputs type `list` where type `int` is expected).
Traceback (most recent call last):
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 776, in convert_to_tensors
    tensor = as_tensor(value)
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 738, in as_tensor
    return torch.tensor(value)
ValueError: expected sequence of length 11 at dim 1 (got 115)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zhiqi/CS839-Project/small_model.py", line 86, in <module>
    trainer.train()
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/transformers/trainer.py", line 2123, in train
    return inner_training_loop(
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/transformers/trainer.py", line 2427, in _inner_training_loop
    batch_samples, num_items_in_batch = self.get_batch_samples(epoch_iterator, num_batches)
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/transformers/trainer.py", line 5045, in get_batch_samples
    batch_samples += [next(epoch_iterator)]
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/accelerate/data_loader.py", line 552, in __iter__
    current_batch = next(dataloader_iter)
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 673, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 55, in fetch
    return self.collate_fn(data)
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/transformers/data/data_collator.py", line 45, in __call__
    return self.torch_call(features)
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/transformers/data/data_collator.py", line 807, in torch_call
    batch = pad_without_fast_tokenizer_warning(
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/transformers/data/data_collator.py", line 66, in pad_without_fast_tokenizer_warning
    padded = tokenizer.pad(*pad_args, **pad_kwargs)
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 3541, in pad
    return BatchEncoding(batch_outputs, tensor_type=return_tensors)
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 240, in __init__
    self.convert_to_tensors(tensor_type=tensor_type, prepend_batch_axis=prepend_batch_axis)
  File "/home/zhiqi/anaconda3/envs/llmmath/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 792, in convert_to_tensors
    raise ValueError(
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (`labels` in this case) have excessive nesting (inputs type `list` where type `int` is expected).
